services:
  app:
    build:
      context: .
      target: web-dev
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - .:/var/www/html
    env_file: .env
    networks:
      - firefly_iii
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=firefly
      - MYSQL_DATABASE=firefly
    ports:
      - "3366:3306"
    networks:
      - firefly_iii
    volumes:
      - firefly_iii_db:/var/lib/mysql
  cron:
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    env_file: .env
    command: sh -c "
      apk add tzdata
      && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime
      | echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/SomeRandomStringOf32CharsExactly;echo\"
      | crontab -
      && crond -f -L /dev/stdout"
    networks:
      - firefly_iii

volumes:
  firefly_iii_db:

networks:
  firefly_iii:
    driver: bridge
